plugins:
  cleanupAttrs: true
  inlineStyles: true
  removeDoctype: true
  removeXMLProcInst: true
  removeComments: true
  removeMetadata: true
  removeTitle: true
  removeDesc: true
  removeUselessDefs: true
  removeXMLNS: false
  removeEditorsNSData: true
  removeEmptyAttrs: true
  removeHiddenElems: true
  removeEmptyText: true
  emoveEmptyContainers: true
  removeViewBox: false
  cleanupEnableBackground: true
  minifyStyles: false
  convertStyleToAttrs: true
  convertColors: true
  convertPathData: true
  convertTransform: true
  removeUnknownsAndDefaults: true
  removeNonInheritableGroupAttrs: true
  removeUselessStrokeAndFill: true
  removeUnusedNS: true
  cleanupIDs: true
  cleanupNumericValues: true
  cleanupListOfValues: true
  moveElemsAttrsToGroup: true
  moveGroupAttrsToElems: true
  collapseGroups: true
  removeRasterImages: true
  mergePaths: true
  convertShapeToPath: true
  sortAttrs: true
  removeDimensions: true
  removeAttrs: true
  removeElementsByAttr: false
  addClassesToSVGElement: false
  addAttributesToSVGElement: false
  removeStyleElement: false
  removeScriptElement: false
  pretty: true
  indent: '2'